# -*- coding: utf-8 -*-
"""Sistemas Numéricos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/laura0965/-/blob/main/clase1/Sistemas_Num%C3%A9ricos.ipynb

# Anterioresutgocvcfyidrtdyrdsikyrs
"""

fib_list=[0,1,1]
n=2
len_=len(str(fib_list[-1]))
while len_<2022:
    fib_list.append(fib_list[n]+fib_list[n-1])
    len_=len(str(fib_list[-1]))
    n+=1
print(len_)
print(n)

# Python program to check if a number
# is a krishnamurthy number
 
# function to calculate the factorial
# of any number
def factorial(n) :
    fact = 1
    while (n != 0) :
        fact = fact * n
        n = n - 1
    return fact
 
# function to Check if number is
# krishnamurthy/special
def isKrishnamurthy(n) :
    sum = 0
    temp = n
    while (temp != 0) :
 
        # calculate factorial of last digit
        # of temp and add it to sum
        rem = temp%10
        sum = sum + factorial(rem)
 
        # replace value of temp by temp / 10
        temp = temp // 10
         
    # Check if number is krishnamurthy
    return (sum == n)
 
# Driver code
for n in range(1,1000)
 if (isKrishnamurthy(n)) :
    print("YES")
    print(n)

"""#ay"""

fib_list=[0,1,1]
n=2
len_=len(str(fib_list[-1]))
while len_<2022:
    fib_list.append(fib_list[n]+fib_list[n-1])
    len_=len(str(fib_list[-1]))
    
    for x in fib_list:
      if x%(7^4)==0:
        n+=1

        print(n)

import math
def es_primo(num):
    t=int(math.sqrt(num))
    for n in range(2,t):
      if num % n == 0:
            print("No es primo", n, "es divisor")
            return False
    print("Es primo")
    return True
es_primo(3457)

fib_list=[0,1,1]
n=2
len_=len(str(fib_list[-1]))
while len_<2022:
    fib_list.append(fib_list[n]+fib_list[n-1])
    len_=len(str(fib_list[-1]))
    n+=1
for x in fib_list:
    if x%(7**4):
      print(n)

answer=[]
n=1
while len(answer)==0:
  for i in range(n)
